server.port=8081

# MS SQL Server Database Config (Next_GO Database)
spring.datasource.url=jdbc:sqlserver://LAPTOP-AVJUVGV1:1433;databaseName=Next_GO;encrypt=true;trustServerCertificate=true;
spring.datasource.username=next_go
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA & Hibernate Settings for SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/ride/
spring.mvc.view.suffix=.jsp